{ inputs, pkgs, system, ... }: {
  home.packages = with pkgs; [
    #aerc
    #awscli2
    binutils
    #(pkgs.chromium.override {
    #  commandLineArgs = "--enable-features=UseOzonePlatform --ozone-platform=wayland --force-dark-mode";
    #})
    cmake
    cowsay
    #deno
    dnsutils
    elixir
    exa
    fd
    file
    fortune
    gcc
    gh
    #gnome3.adwaita-icon-theme
    gnumake
    hexyl
    htop
    hyperfine
    #inputs.status.defaultPackage.${system}
    inputs.tangram.defaultPackage.${system}
    jetbrains.pycharm-community
    jq
    killall
    libreoffice-fresh
    mpv
    neovim
    nodejs-16_x
    nodePackages.http-server
    octaveFull
    okular
    #obs-studio
    #openrgb
    pavucontrol
    #php
    pkg-config
    postgresql
    #pup
    python3
    ripgrep
    #thunderbird
    tokei
    unzip
    usbutils
    vim
    #wally-cli
    xh
    zig
    zoom-us
  ];
}
